# ========================================
# |   Hardcore Farming by ShermansWorld  |
# ========================================

config-version: 1

# =====================================
# |          GENERAL SETTINGS         |
# =====================================

DisableBoneMeal: false
# This setting disables the use of bone meal entirely

# =====================================
# |         PLANT GROWTH RATES        |
# =====================================
# The growrth rates for each plant. Put 1.0 for a vanilla growth rate. 
# Over 1.0 is not supported and will not work.

# Bone meal is affected by growth rates
# The lower the growth rate the more bonemeal it takes to grow something

EnableGrowNerf: true
# Setting this to false will make it so all plants have normal growth rates

BambooGrowthRate: 0.2

BeetrootGrowthRate: 0.2

CactusGrowrthRate: 0.2

CarrotGrowthRate: 0.2

ChorusGrowthRate: 0.2
# Affects the growth of the entire chorus plant

CocoaGrowthRate: 0.2

GlowBerryGrowthRate: 0.2
# Affects the growth of cave vines

KelpGrowthRate: 0.2

MelonGrowthRate: 0.2
# Affects the growth of the stem and melon block

NetherWartGrowthRate: 0.2

PotatoGrowthRate: 0.2

PumpkinGrowthRate: 0.2
# Affects the growth of the stem and the pumpkin block

SweetBerryGrowthRate: 0.2
# Affects the growth rate of the sweet berry bush and berry output

SugarCaneGrowthRate: 0.2

WheatGrowthRate: 0.2


# =====================================
# |   TREE/BIG MUSHROOM GROWTH RATES  |
# =====================================

AcaciaGrowthRate: 0.2

AzaleaGrowthRate: 0.2

OakGrowthRate: 0.2

BirchGrowthRate: 0.2

BrownMushroomGrowthRate: 0.2
# Affects the growth rate of giant brown mushrooms

CrimsonFungusGrowthRate: 0.2

DarkOakGrowthRate: 0.2

JungleGrowthRate: 0.2

MangroveGrowthRate: 0.2

RedMushroomGrowthRate: 0.2
# Affects the growth rate of giant red mushrooms

SpruceGrowthRate: 0.2

WarpedFungusGrowthRate: 0.2

# =====================================
# |        ANIMAL FEED SETTINGS       |
# =====================================
# The amount of feed it takes to breed an animal.

EnableFeedNerf: true

## AxolotlFeedAmount: 5
# Impossible since it takes a bucket of tropical fish

BeeFeedAmount: 5

CatFeedAmount: 5

ChickenFeedAmount: 5

CowFeedAmount: 5

DonkeyFeedAmount: 5

FrogFeedAmount: 5

FoxFeedAmount: 5

GoatFeedAmount: 5

HoglinFeedAmount: 5

HorseFeedAmount: 5

LlamaFeedAmount: 5

MooshroomFeedAmount: 5

OcelotFeedAmount: 5

PandaFeedAmount: 5

PigFeedAmount: 5

RabbitFeedAmount: 5

SheepFeedAmount: 5

StriderFeedAmount: 5

TurtleFeedAmount: 5

WolfFeedAmount: 5



